apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zoo-project-hpgc.fullname" . }}-zoofpm
  labels:
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "zoo-project-hpgc.name" . }}-zoofpm
    app.kubernetes.io/instance: {{ .Release.Name }}-zoofpm
spec:
  {{- if not .Values.zoofpm.autoscaling.enabled }}
  replicas: {{ .Values.zoofpm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zoo-project-hpgc.name" . }}-zoofpm
      app.kubernetes.io/instance: {{ .Release.Name }}-zoofpm
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "zoo-project-hpgc.name" . }}-zoofpm
        app.kubernetes.io/instance: {{ .Release.Name }}-zoofpm
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zoo-project-hpgc.fullname" . }}-processing-manager
      initContainers:
        - name: init-wait-for-dependencies-zoofpm
          image: docker.io/wshihadeh/wait_for:latest
          imagePullPolicy: IfNotPresent
          command: [ "/docker-entrypoint.sh" ]
          args: [ "wait_for", "rabbitmq:{{ .Release.Name }}-rabbitmq"]
          env:
            - name: ZOO_RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
      containers:
        - env:
            - name: ZOO_RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
            - name: STORAGE_CLASS
              value: {{ .Values.workflow.storageClass }}
            - name: DEFAULT_VOLUME_SIZE
              value: "{{ .Values.workflow.defaultVolumeSize }}"
            - name: DEFAULT_MAX_RAM
              value: "{{ .Values.workflow.defaultMaxRam }}"
            - name: DEFAULT_MAX_CORES
              value: "{{ .Values.workflow.defaultMaxCores }}"
            - name: CALRISSIAN_IMAGE
              value: "{{ .Values.workflow.calrissianImage }}"
            {{- if .Values.useKubeProxy }}
            - name: HTTP_PROXY
              value: "http://{{ include "zoo-project-hpgc.fullname" . }}-kubeproxy:8001"
            {{- else }}
            - name: KUBECONFIG
              value: /var/etc/ades/kubeconfig
            {{- end }}

            {{- if .Values.postgresql.enabled }}
            - name: PGHOST
              value: "{{ .Release.Name}}-postgresql-hl"
            - name: PGDATABASE
              value: {{ .Values.global.postgresql.auth.database | quote}}
            - name: PGPASSWORD
              value: {{ .Values.global.postgresql.auth.password | quote}}
            - name: PGUSER
              value: {{ .Values.global.postgresql.auth.username | quote}}
            - name: PGPORT
              value: {{ .Values.global.postgresql.service.ports.postgresql | quote}}
            {{- end }}

            {{- range $k, $v := .Values.workflow.inputs }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}


          name: zoofpm
          image: "{{ .Values.zoofpm.image.repository }}:{{ .Values.zoofpm.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.zoofpm.image.pullPolicy }}
          command: ["/startup.sh"]
          resources: {}
          volumeMounts:
            - name: ades-config
              mountPath: /usr/lib/cgi-bin/main.cfg
              subPath: maincfg
            - name: ades-config
              mountPath: /usr/lib/cgi-bin/oas.cfg
              subPath: oas
            - name: ades-config
              mountPath: /var/www/html/.htaccess
              subPath: htaccess
            - name: startupsh
              mountPath: /startup.sh
              subPath: startUp.sh
            - name: ades-config
              mountPath: {{ .Values.persistence.tmpPath }}/cookiecutter_config.yaml
              subPath: cookiecutter_config

            - name: ades-config
              mountPath: /assets/additional_inputs.yaml
              subPath: additional_inputs
            - name: ades-config
              mountPath: /assets/pod_env_vars.yaml
              subPath: pod_env_vars
            - name: ades-config
              mountPath: /assets/pod_nodeselectors.yaml
              subPath: pod_nodeselectors
            - name: ades-config
              mountPath: /assets/pod_imagePullSecrets.yaml
              subPath: pod_imagePullSecrets

            - name: cwlwrapper-config
              mountPath: /assets/maincwl.yaml
              subPath: maincwl
            - name: cwlwrapper-config
              mountPath: /assets/maincwlmetrics.yaml
              subPath: maincwlmetrics
            - name: cwlwrapper-config
              mountPath: /assets/rules.yaml
              subPath: rules
            - name: cwlwrapper-config
              mountPath: /assets/stagein.yaml
              subPath: stagein
            - name: cwlwrapper-config
              mountPath: /assets/stageout.yaml
              subPath: stageout
            - name: ades-processing-services
              mountPath: {{ .Values.persistence.servicesNamespacePath }}
            - name: tmp-folder
              mountPath: {{ .Values.persistence.tmpPath }}
      restartPolicy: Always
      volumes:
        - name: ades-config
          configMap:
            name: {{ template "zoo-project-hpgc.fullname" . }}-configmap
        - name: cwlwrapper-config
          configMap:
            name: {{ template "zoo-project-hpgc.fullname" . }}-cwlwrapper-configmap
        - name: startupsh
          configMap:
            name: {{ template "zoo-project-hpgc.fullname" . }}-startup-configmap
            defaultMode: 0744
        - name: tmp-folder
          persistentVolumeClaim:
            claimName: {{ template "zoo-project-hpgc.fullname" . }}-tmp-folder

        - name: ades-processing-services
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingProcessingServicesClaim }}
            claimName: {{ .Values.persistence.existingProcessingServicesClaim }}
            {{- else }}
            claimName: {{ template "zoo-project-hpgc.fullname" . }}-processing-services
            {{- end -}}
          {{- else }}
          emptyDir: { }
          {{- end }}
status: {}
