apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: zoo-project-dru-minikube-deployment

build:
  artifacts:
    - image: ghcr.io/zoo-project/zoofpm-eviction-controller
      context: eviction-controller
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "run.sh"
            dest: "/app/"

deploy:
  helm:

    releases:
    - name: zoo-project-dru
      chartPath: zoo-project-dru
      namespace: zoo
      createNamespace: true
      valuesFiles:
      - zoo-project-dru/values_minikube.yaml

    hooks:
      after:
        - host:
            command: ["sh", "-c", "./wait-for-it.sh"]
            os: [darwin, linux]

profiles:

  - name: hostpath
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: [zoo-project-dru/values_apple.yaml]

  - name: keda
    patches:

      - op: add
        path: /deploy/helm/releases/0
        value:
          name: kyverno
          remoteChart: kyverno/kyverno
          version: "3.1.4"
          namespace: kyverno-system
          createNamespace: true
          values:
            crds:
              install: true
            replicaCount: 2
            podDisruptionBudget:
              enabled: true
              minAvailable: 1
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi

      - op: add
        path: /deploy/helm/releases/1/setValues
        value:
          keda.enabled: "true"
          keda.triggers.postgresql.enabled: "true"
          keda.triggers.rabbitmq.enabled: "true"
          keda.kyverno.enabled: "false"
          keda.evictionController.enabled: "true"
          keda.evictionController.image.tag: ""
          keda.kyverno.policies.zoofpmProtection.enabled: "true"
          zoofpm.autoscaling.enabled: "false"

portForward:
# The following port forward is used to access the webui
# - resourceType: service
#   resourceName:	zoo-project-dru-webui
#   namespace: zoo
#   port: 3000
#   localPort: 3058
- resourceType: service
  resourceName:	zoo-project-dru-service
  namespace: zoo
  port: 80
  localPort: 8080
# Websocketd service not available in keda profile  
- resourceType: service
  resourceName:	zoo-project-dru-websocketd
  namespace: zoo
  port: 8888
  localPort: 8888
# S3/Minio services not available in keda profile
- resourceType: service
  resourceName: s3-service
  namespace: zoo 
  port: 9000 
  localPort: 9000 
- resourceType: service
  resourceName: s3-service
  namespace: zoo 
  port: 9001 
  localPort: 9001