apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: zoo-project-dru-minikube-deployment

deploy:
  helm:
    releases:
    - name: zoo-project-dru
      chartPath: zoo-project-dru
      namespace: zoo
      createNamespace: true
      valuesFiles:
      - zoo-project-dru/values_minikube.yaml

    hooks:
      after:
        - host:
            command: ["sh", "-c", "./wait-for-it.sh"]
            os: [darwin, linux]

profiles:

  - name: hostpath
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: [zoo-project-dru/values_apple.yaml]

  - name: keda
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          keda.enabled: "true"
          keda.triggers.postgresql.enabled: "true"
          keda.triggers.rabbitmq.enabled: "true"
          zoofpm.autoscaling.enabled: "false"

portForward:
# The following port forward is used to access the webui
# - resourceType: service
#   resourceName:	zoo-project-dru-webui
#   namespace: zoo
#   port: 3000
#   localPort: 3058
- resourceType: service
  resourceName:	zoo-project-dru-service
  namespace: zoo
  port: 80
  localPort: 8080
- resourceType: service
  resourceName:	zoo-project-dru-websocketd
  namespace: zoo
  port: 8888
  localPort: 8888
- resourceType: service
  resourceName: s3-service
  namespace: zoo 
  port: 9000 
  localPort: 9000 
- resourceType: service
  resourceName: s3-service
  namespace: zoo 
  port: 9001 
  localPort: 9001