{{ if .Values.argo.enabled }}
# Token for Argo Workflows server
---
apiVersion: v1
kind: Secret
metadata:
  name: zoo-project-dru-argo-workflows-server.service-account-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    app.kubernetes.io/component: argo-server-token
  annotations:
    kubernetes.io/service-account.name: zoo-project-dru-argo-workflows-server
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
type: kubernetes.io/service-account-token

# Token for Argo Workflows controller
---
apiVersion: v1
kind: Secret
metadata:
  name: zoo-project-dru-argo-workflows-workflow-controller.service-account-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    app.kubernetes.io/component: argo-controller-token
  annotations:
    kubernetes.io/service-account.name: zoo-project-dru-argo-workflows-workflow-controller
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
type: kubernetes.io/service-account-token
{{ end }}
