{{- if and .Values.argo.enabled .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zoo-project-dru.fullname" . }}-argo-workflows-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    app: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
{{- if and .Values.argo.events .Values.argo.events.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zoo-project-dru.fullname" . }}-argo-events
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    app: argo-events-controller-manager
spec:
  selector:
    matchLabels:
      app: argo-events-controller-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
{{- end }}
{{- end }}
