{{ if .Values.workflow.argo.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    component: argo-workflow
automountServiceAccountToken: true
{{ end }}
