{{- if index .Values "argo-workflows" "server" "enabled" }}
# Fix for ClusterWorkflowTemplates permissions - required to avoid nil pointer in Argo v3.7.1
# Even in namespaced mode, the ClusterWorkflowTemplate informer is created and requires these permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zoo-project-dru.fullname" . }}-argo-server-cluster-template-access
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zoo-project-dru.fullname" . }}-argo-server-cluster-template-access
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zoo-project-dru.fullname" . }}-argo-server-cluster-template-access
subjects:
- kind: ServiceAccount
  name: zoo-project-dru-argo-workflows-server
  namespace: {{ .Release.Namespace }}
{{- end }}
