apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tmp-folder
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "zoo-project-dru.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.tmpAccessMode | quote }}
{{- if .Values.persistence.tmpStorageClass }}
{{- if (eq "-" .Values.persistence.tmpStorageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.tmpStorageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage:  {{ .Values.persistence.tmpSize | quote }}
