apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bin-config
data:
{{- range $path, $_ := .Files.Glob "files/bin/*" }}
  {{ base $path }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end }}
