{{- if and .Values.keda.enabled .Values.keda.evictionController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zoo-project-dru.fullname" . }}-eviction-controller
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
    app.kubernetes.io/component: eviction-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zoo-project-dru.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: eviction-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zoo-project-dru.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: eviction-controller
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-zoo-project-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "zoo-project-dru.fullname" . }}-eviction-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: eviction-controller
        image: {{ .Values.keda.evictionController.image.repository }}:{{ .Values.keda.evictionController.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.keda.evictionController.image.pullPolicy | default "IfNotPresent" }}
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: SCALEDOBJECT_NAME
          value: "{{ include "zoo-project-dru.fullname" . }}-{{ .Values.keda.scaleTargetRef.deployment }}-scaler"

        {{- if (.Values.global.postgresql.auth.existingSecret) }}
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.postgresql.auth.existingSecret }}
              key: password
              optional: true
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.postgresql.auth.existingSecret }}
              key: username
              optional: true
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.postgresql.auth.existingSecret }}
              key: host
              optional: true
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.postgresql.auth.existingSecret }}
              key: port
              optional: true
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.postgresql.auth.existingSecret }}
              key: database
              optional: true
        {{- else }}
        {{- if .Values.postgresql.enabled }}
        - name: PG_HOST
          value: "{{ .Values.postgresql.serviceName }}"
        - name: PG_DATABASE
          value: {{ .Values.global.postgresql.auth.database | quote}}
        - name: PG_PASSWORD
          {{- if .Values.postgresql.useSecret }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.secretName | default (printf "%s-postgresql-secret" (include "zoo-project-dru.fullname" .)) }}
              key: password
          {{- else }}
          value: {{ .Values.global.postgresql.auth.password | quote}}
          {{- end }}
        - name: PG_USER
          value: {{ .Values.global.postgresql.auth.username | quote}}
        - name: PG_PORT
          value: {{ .Values.global.postgresql.service.ports.postgresql | quote}}
        {{- else }}
        # External PostgreSQL (not managed by chart)
        - name: PG_HOST
          value: "postgresql-db-service"
        - name: PG_DATABASE
          value: {{ .Values.global.postgresql.auth.database | quote}}
        - name: PG_PASSWORD
          value: {{ .Values.global.postgresql.auth.password | quote}}
        - name: PG_USER
          value: {{ .Values.global.postgresql.auth.username | quote}}
        - name: PG_PORT
          value: "5432"
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
{{- end }}
