{{- if and .Values.keda.enabled .Values.keda.triggers.postgresql.enabled .Values.keda.triggers.postgresql.useConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zoo-project-dru.keda.postgresql.configmap" . }}
  labels:
    {{- include "zoo-project-dru.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"  # Create ConfigMap before KEDA resources
data:
  query.sql: |
{{ .Files.Get "files/keda/postgresql-scaler-query.sql" | indent 4 }}
{{- end }}