{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ include "zoo-project-dru.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.redis.serviceName }}
spec:
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  selector:
    app: {{ .Values.redis.name }}
    release: {{ .Release.Name }}
  type: ClusterIP
{{- end }}
