{{- if .Values.websocketd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-websocketd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: websocketd
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-websocketd
{{- end }}  