apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kubeproxy
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http-kubeproxy
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-kubeproxy
