workflow:
  storageClass: standard
  inputs:
    APP: zoo-project-hpgc
    STAGEOUT_AWS_REGION: RegionOne
    STAGEOUT_AWS_ACCESS_KEY_ID: minio-admin
    STAGEOUT_AWS_SECRET_ACCESS_KEY: minio-secret-password
    STAGEOUT_AWS_SERVICEURL: http://zoo-project-hpgc-minio.zp.svc.cluster.local:9000
    STAGEOUT_OUTPUT: s3://processingresults

minio:
  # minio chart value parameters description can be found here:
  # https://github.com/bitnami/charts/tree/main/bitnami/minio
  enabled: true
  auth:
    rootUser: minio-admin
    rootPassword: minio-secret-password
    # to access the dashboard from browser run the following port-forward command:
    # kubectl port-forward svc/zoo-project-hpgc-minio 9001:9001 -n zp
  persistence:
    enabled: true
    storageClass: standard
    size: 2Gi
    accessMode: ReadWriteOnce
  defaultBuckets: "processingresults"
  
cookiecutter:
  #templateUrl: https://github.com/EOEPCA/proc-service-template.git
  templateUrl: https://github.com/gfenoy/proc-service-template.git
  templateBranch: zoo-project-dru
