apiVersion: v2
name: zoo-project-dru
description: A Helm chart for ZOO-Project-DRU, a processing platform for EOEPCA with CWL support
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.8.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.34"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

  - name: kyverno
    version: "3.5.2"
    repository: https://kyverno.github.io/kyverno/
    condition: keda.kyverno.enabled

  - name: argo-workflows
    version: "0.45.22"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.enabled

  - name: argo-events
    version: "2.4.8"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.events.enabled

  - name: kube-prometheus-stack
    version: ">=45.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update to the latest ZOO-Project-DRU version, including the latest zoo-calrissian-runner"
      links:
        - name: GitHub Commit
          url: https://github.com/ZOO-Project/ZOO-Project/commit/16dbe5b1b5c68900db69b1dd0ec3ed669dd82875
    - kind: fixed
      description: "Load definition on startup without requiring extra rabbitmq autoSetup"
    - kind: fixed
      description: "Add options for RabbitMQ probes configuration"


  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues