apiVersion: v2
name: zoo-project-dru
description: A Helm chart for Kubernetes
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.26"

dependencies:
  - name: postgresql
    version: "16.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: rabbitmq
    version: "15.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: broker.enabled

  - name: redis
    version: "20.11.4"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: minio
    version: "16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Remove Content-Security-Policy headers to enable Basic HTML UI."
    - kind: security
      description: "Allow only the ZOO-FPM to access the publish.py CGI script."
    - kind: added
      description: "Add support for Knative ClouEvents (without EventPolicy)."
    - kind: added
      description: "Add apache configuration file to pass environment variables required by the ZOO-Kernel."
    - kind: added
      description: "Add documentation to enable knative eventing."
    - kind: changed
      description: "Update the ZOO-Project to the latest version."
      links:
        - name: GitHub Commit
          url: https://github.com/ZOO-Project/ZOO-Project/commit/aeb658e352885d33c3de1d7a3b1bb30878574186

  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues