apiVersion: v2
name: zoo-project-dru
description: A Helm chart for ZOO-Project-DRU, a processing platform for EOEPCA with CWL support
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.32"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: postgresql
    version: "16.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: rabbitmq
    version: "15.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: broker.enabled

  - name: redis
    version: "20.11.4"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: minio
    version: "16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

  - name: kyverno
    version: "3.1.4"
    repository: https://kyverno.github.io/kyverno/
    condition: keda.kyverno.enabled

  - name: argo-workflows
    version: "0.45.22"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.enabled

  - name: argo-events
    version: "2.4.8"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.events.enabled

  - name: kube-prometheus-stack
    version: ">=45.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update to the latest ZOO-Project version with eoap-cwlwrap and cwl2ogc support"
      links:
        - name: GitHub Commit
          url: https://github.com/ZOO-Project/ZOO-Project/commit/39b6fc74b6592b4584be5a0b2740dde11a1ffafc
    - kind: changed
      description: "Update the cwlwrapper-assets templates for stagein and stageout"
    - kind: added
      description: "Add stagein-file.yaml to the ConfigMap"
    - kind: changed
      description: "Update the postgresql scripts to add support for cwl2ogc schema definition"
    - kind: added
      description: "Add processes_profiles section to support profile links in the response headers"
    - kind: changed
      description: "Update the webui to use the latest nuxt-client image (0.0.3)"
      links:
        - name: DockerHub
          url: https://hub.docker.com/r/zooproject/nuxt-client/tags?name=0.0.3

  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues