apiVersion: v2
name: zoo-project-dru
description: A Helm chart for Kubernetes
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.28"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: postgresql
    version: "16.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: rabbitmq
    version: "15.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: broker.enabled

  - name: redis
    version: "20.11.4"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: minio
    version: "16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

  - name: kyverno
    version: "3.1.4"
    repository: https://kyverno.github.io/kyverno/
    condition: keda.kyverno.enabled

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Add KEDA autoscaling support with scale-to-zero functionality and intelligent pod protection."
      links:
        - name: KEDA documentation
          url: https://keda.sh/
    - kind: added
      description: "Implement hybrid scaling logic based on PostgreSQL workers and RabbitMQ queues."
    - kind: added
      description: "Add eviction controller with real-time worker tracking and dynamic pod annotation management."
    - kind: added
      description: "Integrate Kyverno admission policies ensuring zoofpm pods are never deleted while tasks are running."
      links:
        - name: Kyverno documentation
          url: https://kyverno.io/
    - kind: added
      description: "Implement triple protection system: KEDA minReplicas management, eviction controller monitoring, and Kyverno admission control preventing premature pod termination."
    - kind: changed
      description: "Remove the sidecar container from the zoofpm deployment."
    - kind: added
      description: "Add pod-level worker count annotations (zoo-project.org/active-workers) for granular tracking and protection decisions."
    - kind: added
      description: "Add KEDA and Kyverno as chart dependencies with versions 2.14.2 and 3.1.4 respectively."
    - kind: changed
      description: "Update chart documentation with detailed KEDA autoscaling, worker protection strategies, and troubleshooting instructions."

  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues