apiVersion: v2
name: zoo-project-dru
description: A Helm chart for ZOO-Project-DRU, a processing platform for EOEPCA with CWL support
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.9.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.42"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

  - name: kyverno
    version: "3.5.2"
    repository: https://kyverno.github.io/kyverno/
    condition: keda.kyverno.enabled

  - name: argo-workflows
    version: "0.45.22"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.enabled

  - name: argo-events
    version: "2.4.8"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.events.enabled

  - name: kube-prometheus-stack
    version: ">=45.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

  - name: dask-gateway
    version: "2024.1.0"
    repository: https://helm.dask.org/
    condition: dask.enabled

annotations:
  artifacthub.io/changes: |
    - kind: security
      description: "Ensure that every pod runs as a non-root user for better security. The specific non-root user may vary depending on the component and the base image used."
    - kind: changed
      description: "Update the documentation to detail the podSecurityContext and securityContext options for the webui, websocketd, and redis components, and provide guidance on setting appropriate security contexts based on the user that the container runs as."
    - kind: added
      description: "Add extraFromEnv configuration option to allow users to inject additional environment variables from secrets into the ZOO-Kernel-FPM pod."
    - kind: changed
      description: "Update the documentation to reflect the new extraEnvFrom configuration option and provide an example of how to use it to inject environment variables from a secret."
    - kind: changed
      description: "Update the oas.cfg configuration file to add a new hidden process 'Notify' to the list of hidden processes. This process is used internally by the ZOO-Project and should not be exposed to users."
    - kind: changed
      description: "Update nuxt-client to 0.1.1 to ensure the webui also runs as non-root user (for better security)"

  artifacthub.io/license: Apache-2.0

  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues