apiVersion: v2
name: zoo-project-dru
description: A Helm chart for Kubernetes
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.28"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: postgresql
    version: "16.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: rabbitmq
    version: "15.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: broker.enabled

  - name: redis
    version: "20.11.4"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: minio
    version: "16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Add KEDA autoscaling support with scale-to-zero functionality and intelligent pod protection."
      links:
        - name: KEDA documentation
          url: https://keda.sh/
    - kind: added
      description: "Implement hybrid scaling logic based on PostgreSQL workers and RabbitMQ queues."
    - kind: added
      description: "Add pod protection mechanisms preventing termination of pods with active workers registered in PostgreSQL."
    - kind: added
      description: "Add comprehensive KEDA configuration parameters for minReplicas, maxReplicas, pollingInterval, and cooldownPeriod."
    - kind: changed
      description: "Disable traditional HPA when KEDA is enabled to prevent conflicts between autoscaling mechanisms."
    - kind: added
      description: "Add KEDA as a chart dependency with version 2.14.2 from kedacore repository."
    - kind: changed
      description: "Update chart documentation with detailed KEDA autoscaling configuration and monitoring instructions."
    - kind: fixed
      description: "Update to the latest ZOO-Project version to avoid issue with argo dependencies."

  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues