apiVersion: v2
name: zoo-project-dru
description: A Helm chart for ZOO-Project-DRU, a processing platform for EOEPCA with CWL support
home: https://zoo-project.org/
icon: https://avatars.githubusercontent.com/u/10290306?s=200&v=4
source: https://github.com/ZOO-Project/charts/tree/main/zoo-project-dru

maintainers:
  - name: GeoLabs
    url: https://geolabs.fr/
    email: contact@geolabs.fr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.2.29"

keywords:
  - workflows
  - processing
  - eoepca
  - cwl
  - calrissian
  - stac

dependencies:
  - name: postgresql
    version: "16.6.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: rabbitmq
    version: "15.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: broker.enabled

  - name: redis
    version: "20.11.4"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: minio
    version: "16.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
    condition: keda.enabled

  - name: kyverno
    version: "3.1.4"
    repository: https://kyverno.github.io/kyverno/
    condition: keda.kyverno.enabled

  - name: argo-workflows
    version: "0.45.21"
    repository: https://argoproj.github.io/argo-helm
    condition: workflow.argo.enabled

  - name: argo-events
    version: "2.4.8"
    repository: https://argoproj.github.io/argo-helm
    condition: workflow.argo.events.enabled

  - name: kube-prometheus-stack
    version: ">=45.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added ZOO-Project latest version 0.2.29 with Python 3.10"
      links:
        - name: commit
          url: https://github.com/ZOO-Project/ZOO-Project/commit/c29a1da89d5a2d00a4b34af555bcd52dc987df6f
    - kind: added
      description: "Integrated Argo Workflows support with real-time monitoring and event-driven automation"
      links:
        - name: Helm chart
          url: https://artifacthub.io/packages/helm/argo/argo-workflows
    - kind: added
      description: "Added Argo Events integration for real-time workflow event capture and webhook notifications"
      links:
        - name: Helm chart
          url: https://artifacthub.io/packages/helm/argo/argo-events
    - kind: added
      description: "Integrated kube-prometheus-stack with custom Grafana dashboards for workflow metrics visualization"
      links:
        - name: Helm chart
          url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    - kind: added
      description: "Added prometheus-node-exporter"
    - kind: added
      description: "Implemented automatic ServiceMonitor patching to resolve connection refused errors on local environments"
    - kind: added
      description: "Added real-time dashboard refresh (5s intervals) for immediate workflow status updates"
    - kind: added
      description: "Enhanced RBAC permissions for monitoring components access to ServiceMonitors API"
    - kind: added
      description: "Added monitoring.disableProblematicTargets parameter for local development environments"
    - kind: added
      description: "Integrated workflow.argo.events configuration with EventBus, EventSource, and Sensor components"
    - kind: added
      description: "Added argo profile to skaffold configuration for streamlined development workflows"


  artifacthub.io/links: |
    - name: source
      url: https://github.com/ZOO-Project/charts
    - name: support
      url: https://github.com/ZOO-Project/charts/issues