useKubeProxy: true

persistence:
  storageClass: hostpath
  procServicesStorageClass: hostpath
  tmpStorageClass: hostpath

workflow:
  storageClass: hostpath
  argo:
    storageClass: "hostpath"

minio:
  # minio chart value parameters description can be found here:
  # https://github.com/bitnami/charts/tree/main/bitnami/minio
  enabled: true
  persistence:
    enabled: true
    storageClass: hostpath
    size: 2Gi
    accessMode: ReadWriteOnce
  defaultBuckets: "eoepca"
  buckets:
    - name: eoepca
      policy: none
      purge: false
  fullnameOverride: "s3-service"

cookiecutter:
  templateUrl: https://github.com/gfenoy/eoepca-proc-service-template.git
  templateBranch: feature/output-handling

iam:
  enabled: false
  openeoAuth:
    enabled: false

webui:
  enabled: false

websocketd:
  enabled: true

redis:
  enabled: true
